_index:
    path: /
    defaults: { _controller: FTPBundle:Renegade:index }

_login:
    path: /login
    defaults: { _controller: FTPBundle:Login:login }
    methods: GET

_validate:
    path: /login
    defaults: { _controller: FTPBundle:Login:validate }
    methods: POST

_logoff:
    path: /logoff
    defaults: { _controller: FTPBundle:Login:logout }

_user:
    path: /user
    defaults: { _controller: FTPBundle:Users:account }

_user_create:
    path: /user/create
    defaults: {_controller: FTPBundle:Users:getCreate }
    methods: GET

__user_create:
    path: /user/create
    defaults: { _controller: FTPBundle:Users:postCreate }
    methods: POST

_user_view:
    path: /user/view
    defaults: { _controller: FTPBundle:Users:view }

_user_delete:
    path: /user/delete/{id}
    defaults: { _controller: FTPBundle:Users:delete }

_file_upload:
    path: /files/upload
    defaults: { _controller: FTPBundle:Files:upload }