_index:
    path: /
    defaults: { _controller: FTPBundle:Renegade:index }

_login:
    path: /login
    defaults: { _controller: FTPBundle:Login:login }
    methods: GET

_validate:
    path: /login
    defaults: { _controller: FTPBundle:Login:validate }
    methods: POST

_logoff:
    path: /logoff
    defaults: { _controller: FTPBundle:Login:logout }

_user:
    path: /user
    defaults: { _controller: FTPBundle:Users:account }

_user_create:
    path: /user/create
    defaults: {_controller: FTPBundle:Users:getCreate }
    methods: GET
    
_job_create:
    path: /job/create
    defaults: {_controller: FTPBundle:Jobs:getCreate }
    methods: GET

__user_create:
    path: /user/create
    defaults: { _controller: FTPBundle:Users:postCreate }
    methods: POST
    
__job_create:
    path: /job/create
    defaults: { _controller: FTPBundle:Jobs:postCreate }
    methods: POST

_user_view:
    path: /user/view
    defaults: { _controller: FTPBundle:Users:view }
    
_job_view:
    path: /job/view
    defaults: { _controller: FTPBundle:Jobs:view }

_user_delete:
    path: /user/delete/{id}
    defaults: { _controller: FTPBundle:Users:delete }
    
_job_delete:
    path: /job/delete/{id}
    defaults: { _controller: FTPBundle:Jobs:delete }
    

